### Numpy (NumericPython)

In [1]:
!pip install numpy

In [1]:
import numpy as np
# ndarray
n1 = np.array([10,20,30,40,50])
n1

array([10, 20, 30, 40, 50])

In [4]:
p1 = [1,2,3,4,5]
p1

[1, 2, 3, 4, 5]

In [5]:
type(n1)

numpy.ndarray

In [6]:
type(p1)

list

In [7]:
# ND => N dimensional

In [2]:
py_list = list(range(1_000_000)) # 1m python array
np_array = np.array(py_list) # 1m numpy array

In [3]:
%%timeit
[x+1 for x in py_list]

29.5 ms ± 1.13 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
%%timeit
np_array + 1

1.09 ms ± 13.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [14]:
### Scalar,Vector,Matrix,Tensor
### 1D, 2D, 3D ndarrayler
### Transpoz, Diskr.

In [5]:
scalar_arr = np.array(1)
scalar_arr

array(1)

In [13]:
vector_arr = np.array([ 10, 20, 30 ])
vector_arr

array([10, 20, 30])

In [ ]:
#Arrayin boyutunu öğrenmek
# ndim -> n dimension
vector_arr.ndim

In [10]:
vector_arr2 = np.array([ 50, 60, 70 ])
vector_arr2

array([50, 60, 70])

In [11]:
# Arrayler arası işlemler (Vector)
result = vector_arr + vector_arr2
result

array([ 60,  80, 100])

#### ! (Shape) Şekil arrayler arası işlem için uyuşma sağlamalıdır.!

In [20]:
arr1 = np.array([10,20])
arr2 = np.array([30,40,50])

arr1.shape, arr2.shape, arr1+arr2

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [23]:
arr3 = np.array(
    [
        [ 10, 20, 30 ],
        [ 30, 40, 50 ]
    ] 
) 
arr3.ndim, arr3.shape

(2, (2, 3))

In [24]:
arr4 = np.array(
    [
        [60,70,80],
        [90,100,110]
    ]
)
arr4.ndim, arr4.shape

(2, (2, 3))

In [26]:
result = arr3+arr4
result

array([[ 70,  90, 110],
       [120, 140, 160]])

In [27]:
result2 = arr4 - arr3
result2

array([[50, 50, 50],
       [60, 60, 60]])

In [28]:
arr5 = np.array([
    [30,40],
    [50,60],
    [70,80]
])
arr5.ndim, arr5.shape

(2, (3, 2))

In [29]:
# (2,3) shape ile (3,2) shape matris toplamı?
# Shapelerin uygun olması lazım
arr4+arr5

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [31]:
# Reshape işlemi.
#    [30,40],
#    [50,60],
#    [70,80]
arr4 + arr5.reshape(2,3)

array([[ 90, 110, 130],
       [150, 170, 190]])

In [33]:
arr4 * arr5.reshape(2,3)

array([[1800, 2800, 4000],
       [5400, 7000, 8800]])

In [37]:
# Dot Product -> İç Çarpım, Nokta Çarpım
#arr4.shape,arr5.shape
# İlk matrisin sütun sayısı, ikinci matrisin satır sayısına eşit olmalı.
result = np.dot(arr4, arr5)
result

array([[10900, 13000],
       [15400, 18400]])

In [38]:
arr4, arr5

(array([[ 60,  70,  80],
        [ 90, 100, 110]]),
 array([[30, 40],
        [50, 60],
        [70, 80]]))

In [39]:
# İç çarpıma nerede ihtiyaç duyarız? -> Benzerlik, Projeksiyon, Lineer Kombinasyon

# Tensor

In [41]:
tensor1 = np.array(
    [
        [ [10,20], [30,40], [50,60]  ],
        [ [70,80], [90,100], [110,120]  ],
        [ [70,80], [90,100], [110,120]  ],
        [ [70,80], [90,100], [110,120]  ]
    ]
)
tensor1.ndim, tensor1.shape

(3, (4, 3, 2))

In [42]:
tensor1.size

24

In [43]:
tensor2 = np.random.randint(0, 256, (100,100,3))
tensor2

array([[[156,  85,  24],
        [236, 166,  42],
        [ 10, 105, 236],
        ...,
        [ 34, 190, 160],
        [129, 105, 191],
        [234,  63, 118]],

       [[ 83,  60,  35],
        [ 30, 120,  21],
        [244,  66, 174],
        ...,
        [174, 109,  27],
        [186, 231, 191],
        [ 83,  25,  65]],

       [[ 21,  91,   3],
        [102, 231, 137],
        [ 98, 141, 126],
        ...,
        [ 43, 119, 144],
        [105,  62, 254],
        [175,  18, 189]],

       ...,

       [[252, 152,   6],
        [236, 248, 116],
        [ 36,  60,  93],
        ...,
        [ 52, 125, 231],
        [210, 122,  87],
        [ 69,  71, 182]],

       [[248, 251, 158],
        [ 63,  11, 135],
        [254, 116,  96],
        ...,
        [193,  46, 217],
        [162, 143,  55],
        [ 70, 117, 126]],

       [[121,  87,  95],
        [121, 180, 155],
        [ 85,  17,  34],
        ...,
        [233, 213,  93],
        [126,  84, 208],
        [ 26,  61, 125]]

In [44]:
from PIL import Image

In [45]:
image = Image.open("kedi.jpg")

In [46]:
image_array = np.array(image)

In [47]:
image_array.shape

(1500, 1000, 3)

In [48]:
image_array

array([[[ 92,  87,  84],
        [ 92,  87,  84],
        [ 92,  87,  84],
        ...,
        [ 96, 101, 104],
        [ 99, 104, 107],
        [101, 106, 109]],

       [[ 92,  87,  84],
        [ 92,  87,  84],
        [ 92,  87,  84],
        ...,
        [ 96, 101, 104],
        [ 99, 104, 107],
        [101, 106, 109]],

       [[ 92,  87,  84],
        [ 92,  87,  84],
        [ 92,  87,  84],
        ...,
        [ 96, 101, 104],
        [ 99, 104, 107],
        [101, 106, 109]],

       ...,

       [[  2,   2,   4],
        [  2,   2,   4],
        [  2,   2,   4],
        ...,
        [ 35,  25,  23],
        [ 35,  25,  23],
        [ 35,  25,  23]],

       [[  2,   2,   4],
        [  2,   2,   4],
        [  2,   2,   4],
        ...,
        [ 36,  26,  24],
        [ 36,  26,  24],
        [ 36,  26,  24]],

       [[  3,   3,   5],
        [  3,   3,   5],
        [  3,   3,   5],
        ...,
        [ 37,  27,  25],
        [ 37,  27,  25],
        [ 37,  27,  25]]