### Numpy (NumericPython)

In [1]:
!pip install numpy

In [1]:
import numpy as np
# ndarray
n1 = np.array([10,20,30,40,50])
n1

array([10, 20, 30, 40, 50])

In [4]:
p1 = [1,2,3,4,5]
p1

[1, 2, 3, 4, 5]

In [5]:
type(n1)

numpy.ndarray

In [6]:
type(p1)

list

In [7]:
# ND => N dimensional

In [2]:
py_list = list(range(1_000_000)) # 1m python array
np_array = np.array(py_list) # 1m numpy array

In [3]:
%%timeit
[x+1 for x in py_list]

29.5 ms ± 1.13 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
%%timeit
np_array + 1

1.09 ms ± 13.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [14]:
### Scalar,Vector,Matrix,Tensor
### 1D, 2D, 3D ndarrayler
### Transpoz, Diskr.

In [5]:
scalar_arr = np.array(1)
scalar_arr

array(1)

In [7]:
vector_arr = np.array([ 10, 20 , 30 ])
vector_arr

array([10, 20, 30])

In [9]:
#Arrayin boyutunu öğrenmek
# ndim -> n dimension
vector_arr.ndim

1

In [10]:
vector_arr2 = np.array([ 50, 60, 70])
vector_arr2

array([50, 60, 70])

In [11]:
# Arrayler arası işlemler (Vector)
result = vector_arr + vector_arr2
result

array([ 60,  80, 100])